# settings.yaml
# box_name: "bento/ubuntu-22.04"
box_name: "bento/debian-12"
vm:
- name: "controlplane"
  ip: "192.168.201.10"
  memory: "4096"
  cpus: "3"
- name: "node01"
  ip: "192.168.201.11"
  memory: "4096"
  cpus: "3"
# - name: "node02"
#   ip: "192.168.201.12"
#   memory: "2048"
#   cpus: "1"